### PR TITLE
Hide android cursor

### PR DESCRIPTION
**Pull request by dragonstormmk2**
I cant take ownership of this code. @xoureldeen did it first but Winlator-Frost is more stable imo. so i added the code for the hidden android cursor to a fork of it in hopes that youll merge the code in the next update. Or so.

### CODE REVIEW

**Comment by xoureldeen** [comment]
:)

**Review by MrPhryaNikFrosty — APPROVED** [review]

**Review by MrPhryaNikFrosty — APPROVED** [review]

**Review by MrPhryaNikFrosty — APPROVED** [review]

**Comment by MrPhryaNikFrosty** [comment]
Merged done

**Review by MrPhryaNikFrosty — COMMENTED** [review]
.

**Comment by longjunyu2** [comment]
What is "Odin 2 users or external gamepad will facing the xinput issue (like joystick issue) in latest glibc due to newest wine version" ？ Are you serious? I am an Odin2 user.

**Comment by longjunyu2** [comment]
Sorry this is off topic but you did not allow issue.

**Comment by MrPhryaNikFrosty** [comment]
Bc I heard someone reported to me that my winlator have a joystick issue which left stick analog not working or working like a mouse. But maybe it's only happen in my mod

**Comment by MrPhryaNikFrosty** [comment]
> @MrPhryaNikFrosty What is "Odin 2 users or external gamepad will facing the xinput issue (like joystick issue) in latest glibc due to newest wine version" ？ Are you serious? I am an Odin2 user.

Bc I heard someone reported to me that my winlator have a joystick issue which left stick analog not working or working like a mouse. But maybe it's only happen in my mod

**Comment by longjunyu2** [comment]
@MrPhryaNikFrosty it is a cmod issue maybe... I do all tests on Odin2 so I think this should not happen. Sorry to bother you.

**Pull request merged**
